name: CI

on:
  push:
    paths:
      - ".github/workflows/ci.yml"
      - "**.cs"
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        dotnet-version: [6.0, 8.0]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install Android Workload
        run: |
          dotnet workload install android --skip-manifest-update || echo "Android workload already installed"

      - name: Restore Dependencies
        run: |
          dotnet restore
          dotnet workload restore || echo "No workloads to restore"

      - name: Build Solution
        run: dotnet build --configuration Release --no-restore

  test:
    name: Test Examples
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        dotnet-version: [6.0, 8.0]
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Run Examples
        shell: bash
        run: |
          shopt -s nullglob
          for proj in examples/*/*.csproj; do
            echo "Running example: $proj"
            dotnet run --project "$proj" --configuration Release
          done

  lint:
    name: Lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        dotnet-version: [6.0, 8.0]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dotnet-format
        run: |
          if ! dotnet tool list -g | grep -q dotnet-format; then
            dotnet tool install -g dotnet-format
          fi
          export PATH="$PATH:$HOME/.dotnet/tools"

      - name: Run Linter
        run: dotnet format --check