name: Build & Deploy Docs

on:
  push:
    paths:
      - 'docs/**'     
  pull_request:
    paths:
      - 'docs/**'         
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install DocFX
        run: dotnet tool install -g docfx

      - name: Build Docs
        run: docfx build -o _site

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site

  deploy:
    if: github.event_name == 'push'  # Only deploy on actual pushes, not PRs
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      pages: write
    steps:
      - name: Download built site
        uses: actions/download-artifact@v4
        with:
          name: site
          path: _site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
